export const ALL_ITEMS = 'Item/allItems'
export const GET_ITEM = 'Item/getItem'
export const BOOK = 'Item/bookItem'
export const EDIT_ITEM = 'Item/editItem'
export const CREATE_ITEM = 'Item/createItem'
export const DELETE_ITEM = 'Item/deleteItem'
