version: '2'
services:

  # The Application
  app:
    restart: always
    build:
      context: ./
      dockerfile: dockerConfig/docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      PHP_IDE_CONFIG: "serverName=php-fpm"
      DB_PORT:        "3306"
      DB_HOST:        "mysql"

  # The Web Server
  web:
    restart: always
    build:
      context: ./
      dockerfile: dockerConfig/docker/web.dockerfile
    working_dir: /var/www
    depends_on:
      - mysql
      - app
    volumes_from:
      - app
    ports:
      - 82:80

  # The Database
  mysql:
    image: mysql:8.0
    # PDO Doesn't support MySQL 8 caching_sha2_password Authentication
    # @see https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    command: --default-authentication-plugin=mysql_native_password
    depends_on:
      - app
    restart: always
    ports:
      - 33062:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ddhlumen
      MYSQL_ROOT_PASSWORD: secret

  redis:
    image: redis
    ports:
      - "6379:6379"


  frontend:
    restart: always
    build:
      context: ./
      dockerfile: dockerConfig/docker/node.dockerfile
    ports:
      - "3000:3000"


volumes:
  mysql:
